name: Mazeball Container Build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    
    - name: ls
      run: |
        ls

    #- name: Login to Docker Hub
    #  uses: docker/login-action@v2
    #  with:
    #    username: ${{ secrets.DOCKERHUB_USERNAME }}
    #    password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: DockerBuild
      run: |
        #$tag=(get-date -format yyMMddhhmm)
        #$image="${{ secrets.DOCKERHUB_USERNAME }}/mazeballweb:$tag"
        cd 1/debian-11/
        ls
        docker build -t .
        docker images
        #docker push $image
